os: linux
dist: bionic

language: rust
rust:
  - stable
#  - beta
#  - nightly

env:
  jobs:
    - PKG_VERSION=0.10.0

addons:
  apt:
    packages:
      - wget
      - autoconf
      - libtool
      - libssl-dev
      - libxml2-dev
      - build-essential
      - ejabberd

before_script:
  - wget -q -O- https://github.com/strophe/libstrophe/archive/$PKG_VERSION.tar.gz | tar -xzC ~/build
  - pushd ~/build/libstrophe-$PKG_VERSION
  - ./bootstrap.sh
  - ./configure --prefix=/usr
  - sudo make -j"$(nproc)" install
  - popd
  - sudo systemctl start ejabberd
  - echo -n libstrophe@localhost > jid.txt
  - echo -n NbgNU3fTFu > password.txt
  - sudo ejabberdctl register libstrophe localhost NbgNU3fTFu

script:
  - cargo test -v --features=creds-test -- --test-threads=1
  - cargo test -v --release --features=creds-test -- --test-threads=1

jobs:
  allow_failures:
    - rust: nightly
