sudo: true
dist: bionic

language: rust
rust:
  - stable
  - beta
  - nightly

env:
  matrix:
    - PKG_VERSION=0.9.3

addons:
  apt:
    packages:
      - wget
      - autoconf
      - libtool
      - libssl-dev
      - libxml2-dev
      - build-essential

before_script:
  - wget -q -O- https://github.com/strophe/libstrophe/archive/$PKG_VERSION.tar.gz | tar -xzC ~/build
  - pushd ~/build/libstrophe-$PKG_VERSION
  - ./bootstrap.sh
  - ./configure --prefix=/usr
  - sudo make -j"$(nproc)" install
  - popd

matrix:
  allow_failures:
    - rust: nightly
