[package]
name = "libstrophe"
version = "0.12.2"
edition = "2018"
description = "Rust ergonomic wrapper for libstrophe"
keywords = ["jabber", "xmpp", "libstrophe", "messaging", "im"]
categories = ["api-bindings", "network-programming"]
authors = ["Pro <twisted.fall@gmail.com>"]
license = "LGPL-3.0"
documentation = "https://docs.rs/libstrophe"
readme = "README.md"
repository = "https://github.com/twistedfall/libstrophe"

[badges]
travis-ci = { repository = "twistedfall/libstrophe", branch = "master" }

[dependencies]
bitflags = "1.0"
lazy_static = "1.2"
log = {version = "0.4", optional = true}
num = "0.2"
scopeguard = "1.0"
sys = {package = "libstrophe-sys-bindgen", version = "2.1"}

[dev-dependencies]
env_logger = "0.7"
matches = "0.1"
trybuild = "1.0"

[features]
default = ["rust-log", "libstrophe-0_9_2", "libstrophe-0_9_3"]
libstrophe-0_9_2 = []
libstrophe-0_9_3 = []
rust-log = ["log"]
creds-test = []
