name: libstrophe
on:
  push:
    branches:
      - "*"
    tags_ignore:
      - "*"
  pull_request:
    branches:
      - "*"
jobs:
  ci:
    runs-on: ubuntu-20.04
    env:
      PKG_VERSION: 0.12.2
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: ci/install.sh
        shell: bash

      - uses: dtolnay/rust-toolchain@stable

      - name: Clippy
        run: ci/clippy.sh
        shell: bash

      - name: Test
        run: ci/script.sh
        shell: bash
