name: libstrophe
on:
  push:
    branches:
      - "*"
    tags_ignore:
      - "*"
  pull_request:
    branches:
      - "*"
jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        libstrophe-version:
          - 0.9.3
          - 0.10.1
          - 0.11.0
          - 0.12.2
    runs-on: ubuntu-20.04
    env:
      LIBSTROPHE_VERSION: ${{ matrix.libstrophe-version }}
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: ci/install.sh
        shell: bash

      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy,rustfmt

      - name: Checks
        run: ci/checks.sh
        shell: bash

      - name: Test
        run: ci/script.sh
        shell: bash

  msrv:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Get MSRV package metadata
        id: metadata
        run: cargo metadata --no-deps --format-version 1 | jq -r '"msrv="+(.packages[]|select(.name=="libstrophe").rust_version)' >> $GITHUB_OUTPUT

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ steps.metadata.outputs.msrv }}
          components: clippy,rustfmt

      - name: Checks
        run: ci/checks.sh
        shell: bash
